build:
  type: web
  name: crackit-backend
  runtime: python
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --ws websockets --loop asyncio
  envVars:
    - key: MONGO_URL
      sync: false
    - key: DB_NAME
      sync: false
    - key: JWT_SECRET
      sync: false
    - key: GEMINI_API_KEY
      sync: false
    - key: CORS_ORIGINS
      value: https://crackit-ai-frontend.onrender.com,https://frontend-f1lh.onrender.com